### ISSUE TITLE
Should aliases be persistent?

### ISSUE THREAD

**Issue by zzamboni** [zzamboni/elvish-modules#1]
The alias module at the moment automatically saves aliases defined with `alias:new` to individual files under `~/.elvish/aliases/`. This is nice for interactive use, but I am not convinced of this being a good thing. For the most part, aliases should be defined in the config file, and I think it is a good thing that, if they need to be persistent, they should be defined there so that the config file is a "single source of truth". Maybe a new `alias:save` function could be added for when you want to save certain aliases, but not be the default behavior.

**Comment by iwoloschin** [comment]
This kind of reminds me of fish's function/funced/funcsave features, which I both love and hate, mostly because I would often forget to actually save the function (or more often changes to an existing function) before exiting the shell.  On the other hand, they're fairly straightforward to use and do allow easy testing of new functions (aliases) without too much trouble, and nothing is permanent unless you explicitly make it so.

One problem with fish's approach is that all function definitions are stored in separate files, under fish's configuration directory.  In practice this actually works reasonably well, particularly if you have more complex functions defined that would make for a busy configuration file, but it does go directly against the "single source of truth" idea.

**Comment by zzamboni** [comment]
@iwoloschin thanks for your feedback - I was in fact thinking about fish's model when I wrote the above. I am very much in favor of "single source of truth" configuration, which is why I try to make all my config files as self-contained as possible, and having those separate files under `~/.elvish/aliases` has been troubling me.

I'm thinking I will modify `alias` to mimic the fish model: automatically loading any persisted aliases by default, don't save new ones by default, but provide a function to do so.

Once we get [closure introspection](https://github.com/elves/elvish/issues/560), it should be possible to implement a `funced` function as well :)

**Comment by krader1961** [comment]
One of the reasons I stopped using your alias module is its automatic caching of the definition. If the expectation is that the alias:new appears in the ~/.elvish/rc.elv file there isn't any reason to cache the definition. Anyone defining an alias interactively can be expected to add the command to their rc.elv if they want it to make it permanent. It's not obvious an `alias:save $fn_name`, to mimic fish's `funcsave`, is worthwhile but it would be trivial to support. I was bitten more than once by removing an alias:new from my rc.elv and forgetting to remove the cached definition.
