### ISSUE TITLE
semver module: missing MINOR, PATCH should not be ignored

### ISSUE THREAD

**Issue by zzamboni** [zzamboni/elvish-modules#17]
(Reported by @krader1961)

According to the [documentation](https://semver.org/#spec-item-2):
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers

Currently semver considers missing Y or Z as zeros, so that:
```
> semver:eq 1.0 1.0.0
▶ $true
```
This should produce an error - maybe there should be a `&non-strict` option to allow parsing non-strictly-compliant numbers.

**Comment by krader1961** [comment]
There is also the question of how blatantly invalid semvers are handled; e.g., "`x.y.z`". IMHO all such cases should throw an exception by default and the user should have to explicitly use a `&nonstrict` option if they want to be lenient. The exception being a "v" (or "V") prefix since far too many otherwise valid semantic version strings include that invalid prefix.

**Comment by zzamboni** [comment]
I think I'm going to do some work on the module adding the [official regular expression](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) to check for validity. A `&nonstrict` option would allow a `[Vv]` at the beginning, but probably no more.

**Comment by krader1961** [comment]
> I think I'm going to do some work on the module adding the official regular expression....

I think that is a good idea. Note that a leading "v" was valid in SemVer 1.0.0 but is invalid in the 2.0.0 spec. No idea why that change was made but even if it is a good idea for the SemVer spec I think a "v" prefix should be silently ignored if the string is otherwise valid. That is, always preface the official regexp with `[vV]?`. Obviously that's just my opinion and opinions are like assholes: everyone has one. 😄 It is perfectly reasonable to make the default behavior strictly conforming and require a `&nonstrict` option if the user wants to be lenient on this point. I've created PR https://github.com/elves/elvish/pull/1348 that incidentally removes the leading "v" from the Elvish semver string.

**Comment by zzamboni** [comment]
@krader1961 please check out https://github.com/zzamboni/elvish-modules/pull/18.

**Comment by zzamboni** [comment]
I think #18 addresses this issue, so I'm closing it. @krader1961 feel free to reopen if there's something still missing.
